### ISSUE TITLE
User Story: Install required packages

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#11]
As a **Developer**, I would like to **install the packages/libraries I need**, so that **I can prepare my development environment**.

### Tasks:
- [x] Task 1 – Install dj_database_url and psycopg2
- [x] Task 2 – Install Django AllAuth
- [x] Task 3 – Install Bootstrap 4 for Crispy Forms
- [x] Task 4 –  Install Summernote
- [x] Task 5 –  Install Crispy Forms
- [x] Task 6 –  Install Stripe
- [x] Task 7 –  Install Django Countries
- [x] Task 8 –  Install Gunicorn
- [x] Task 9 –  Install boto3 and django-storages
- [x] Task 10 – Create a requirements.txt file

### Epic:  #1
