### ISSUE TITLE
User Story: Create the first app

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#12]
As a **Developer**, I would like to **create the first app (profiles)**, so that **I can start working on user authentication**.

### Tasks:
- [x] Task 1 – Create the Profiles app
- [x] Task 2 – Create the Profile model connected to the User model
- [x] Task 3 – Set up user login/account creation with AllAuth

### Epic: #1
