### ISSUE TITLE
User Story: Mark and save a product as "favourite"

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#27]
As a **User (Customer)**, I would like to be able to **save my favourite products to a wishlist in my profile/account**, so that **I can find them easily when I am ready to buy them**.

### Acceptance Criteria

- Acceptance Criteria 1
**Given** that I am a user
**When** I navigate to the shop page
**Then** I can tap/click/select a heart icon next to any product.
- Acceptance Criteria 2
**Given** that I am a logged in user
**When** I tap the heart icon next to a specific product
**Then** that product is automatically saved to the wishlist in my profile/account.
- Acceptance Criteria 3
**Given** that I am a user who is not logged in
**When** I tap the heart icon next to a specific product
**Then** a notification telling me to log in pops up.

### Tasks
- [x] Task 1 – Add a heart icon next to each product, both on the shop page, and on a product detail page
- [x] Task 2 – Create a functionality that saves the product to a list of favourites" if the user is logged in
- [x] Task 3 – Show a message prompting a user to log in in order to mark a product as "favourite" if they are not logged in
- [x] Task 4 – Make the heart icon accessible to keyboard users as well

### Epic: #4
