### ISSUE TITLE
User Story: Add a product/products to the basket

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#30]
As a **User (Customer)**, I would like to be able to **add products that I want to buy to my shopping basket**, so that I can **purchase them**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** That I am an unregistered user
**When** I find a product I want to purchase and I click on "add to basket"
**Then** the product is added to my shopping basket.
- Acceptance Criteria 2
**Given** That I am a registered and logged in user
**When** I find a product I want to purchase and click "add to basket"
**Then** the product is added to my shopping basket.
- Acceptance Criteria 3
**Given** that I am a user,
**When** I click add to cart on a product that is already in my basket
**Then** the quantity of that product in my basket increases by the defined amount.

### Tasks
- [x] Task 1 – Develop a shopping basket functionality to track products the user wants to purchase
- [x] Task 2 – Make the basket functionality accessible for both logged in and not logged in/unregistered users
- [x] Task 3 – Develop a method to check whether a product already exists in the basket – if the product exists, increase quantity as required

### Epic: #5
