### ISSUE TITLE
User Story: View the basket

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#31]
As a **User (Customer)**, I would like to be able to **view the contents of my shopping basket**, so that **I can confirm that it contains all the products I want to buy in correct quantities before proceeding to purchase**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a user
**When** I click on the shopping basket in the nav bar
**Then** I am taken to a page with the details of all the products I have in my basket.
- Acceptance Criteria 2
**Given** that I am a user
**When** I add a product to my cart
**Then** I receive a visual confirmation that the product was added to my basket.

### Tasks
- [x] Task 1 – Develop a page for viewing the shopping basket
- [x] Task 2 – Develop a temporary preview of the shopping cart to display when adding a product to the cart (on medium and larger screens)
- [x] Task 3 – Display number of products in the basket next to the basket icon in the navbar

### Epic: #5
