### ISSUE TITLE
User Story: Save the shoppping basket for later

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#34]
As a **User (Customer)**, I would like to be able to **save my shopping basket for later**, so that **I can come back and make the purchase at a convenient time**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a logged in user
**When** I have products in my shopping basket
**Then** my basket is automatically saved in my account.
- Acceptance Criteria 2
**Given** that I am a logged in user
**When** I have items in my shopping basket that I saved previously
**Then** I have the ability to easily access that exact basket when I am logged into my account.

### Tasks
- [ ] Task 1 – Develop a way for logged in users to save their shopping basket to access at a later time
- [ ] Task 2 – Develop a way for logged in users to easily access a saved shopping basket
- [ ] Task 3 – Ensure a basket is removed from a logged in user's account as soon as they complete the checkout process.

### Epic: #5
