### ISSUE TITLE
User Story: Provide personal details needed in the checkout process

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#37]
As a **User (Customer)**, I would like to be able to **provide my details**, so that **my order can be processed**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a user who is not logged in
**When** I proceed to checkout
**Then** I am asked to enter my shipping and billing address
- Acceptance Criteria 2
**Given** that I am a user who is not logged in
**When** I enter my billing address
**Then** I can use the same address as my shipping address without having to fill it out twice.
- Acceptance Criteria 3
**Given** that I am a logged in user,
**When** I enter my billing and shipping address details,
**Then** I have the option to save them to my account.
- Acceptance Criteria 4
**Given** that I am a logged in user and there are address details saved in my account
**When** I get to the enter billing and shipping address page
**Then** I have the option to use previously saved details.
- Acceptance Criteria 5
**Given** that I am a registered user and I am not logged in
**When** I proceed to enter the address information
**Then** I have the ability to log in to my account and then return to the same page and use previously saved address details.

### Tasks
- [x] Task 1 – Develop checkout page to collect billing and delivery address details
- [x] Task 2 – Enable option to use billing address for delivery address
- [x] Task 3 – Enable option for users to save address details to their account
- [x] Task 4 – Enable link to login which redirects back to checkout page
- [x] Task 5 – Enable logged in users to select previously saved addresses instead of manual completion of the form

### Epic: #6
