### ISSUE TITLE
User Story: Pay for the items in the shopping basket

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#38]
As a **User (Customer)**, I would like to be able to **use my credit/debit card to make a purchase**, so that **I can pay for my items easily and I can receive my order**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a user
**When** checking out my shopping basket
**Then** I have the ability to enter my credit/debit card details securely.
- Acceptance Criteria 2
**Given** that I am a user
**When** I enter my card details to pay for the transaction
**Then** my payment will be processed.
- Acceptance Criteria 3
**Given** that I am a user
**When** I enter my card details and click/tap "buy"
**Then** I am kept informed as to the status of the transaction as it progresses.
- Acceptance Criteria 4
**Given** that I am a user
**When** my payment fails
**Then** I am redirected back to the checkout page without losing all the inputted information so that I can try again or with a different card.
- Acceptance Criteria 5
**Given** that I am a user
**When** I check out and my payment is processed successfully
**Then** I am taken to a confirmation page.

### Tasks
- [x] Task 1 – Develop secure form to capture credit card details
- [x] Task 2 – Develop link to payment processor
- [x] Task 3 – Develop message system to keep customer informed of processing status
- [x] Task 4 – Develop redirect to appropriate page depending on payment outcome

### Epic: #6
