### ISSUE TITLE
User Story: Receive an order confirmation

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#39]
As a **User (Customer)**, I want to **be shown a confirmation page when my payment is accepted and my order is placed**, so that **I can see that my order will be processed**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am a user
**When** I complete the checkout process and my payment is accepted
**Then** I can see a confirmation page with my order details.
- Acceptance Criteria 2
**Given** that I am a user
**When** I complete the checkout process and my payment is accepted
**Then** I receive a confirmation email with my order details.
- Acceptance Criteria 3
**Given** that I am a registered user and I was logged in when I placed my order
**When** I have completed the checkout process and my payment was accepted
**Then** my order appears in my user account.

### Tasks
- [x] Task 1 – Create an order confirmation page that is shown to the user when they successfully complete the checkout process
- [x] Task 2 – Develop an automated order confirmation email containing all important order details

- [x] Task 3 – Link a new order to a user so that it is visible in the user's profile/account
- [x] Task 4 – Ensure each order has a unique id number

### Epic: #6
