### ISSUE TITLE
User Story: Research and apply suitable keywords

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#45]
As a **Developer**, I want to **research and apply the best keywords**, so that **the web application ranks higher on search engines**.

### Tasks
- [x] Task 1 – Brainstorm short and long keywords
- [x] Task 2 – Research the keywords you came up with on Google to check related searches or autocomplete suggestions
- [x] Task 3 – Refine the list of keywords based on your research
- [x] Task 3 – Use the keywords in meta tags and in the flow of the website's content where suitable

### Epic: #8
