### ISSUE TITLE
User Story: Save an article/recipe to a user profile

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#49]
As a **User (Customer)**, I would like to be able to **save my favourite blog articles and recipes to my profile** so that **I can access them easily in the future**.

- Acceptance Criteria 1
**Given** that I am a logged in user
**When** I navigate to any blog post (article/recipe)
**Then** I can save the post to my account to easily find it in the future.
- Acceptance Criteria 2
**Given** that I am a logged in user
**When** I navigate to my user profile/account
**Then** I can see and easily access all my saved blog posts.

### Tasks
- [x] Task 1 – Add a "save" icon to the blog article/recipe template
- [x] Task 2 – Create the functionality to save an article/recipe to the profile for any logged-in user when they click the icon
- [x] Task 3 – Ensure there is a section of the user account where each user can see their saved articles/recipes

### Epic: #9
