### ISSUE TITLE
User Story: Sign up to a webinar on health- an wellness-related topics

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#50]
As a **User (Customer)**, I would like to be able to **attend online events organised by the store** so that **I can be a part of a community of like-minded people who are interested in health and wellness**.

- Acceptance Criteria 1
**Given** that I am a user
**When** I go to the main navigation
**Then** I can access a page with details of upcoming webinars.
- Acceptance Criteria 2
**Given** that I am a registered user
**When** I navigate to the page with upcoming webinars
**Then** I can sign up for any of them.
- Acceptance Criteria 3
**Given** that I am a registered and logged-in user
**When** I sign up for a webinar
**Then** I can see it in my profile/account.
-Acceptance Criteria 4
**Given** that I am an unregistered/logged-out user
**When** I go to the page with upcoming webinars
**Then** I can see the option to sign up/log in so that I can sign up for the webinar.

### Tasks
- [x] Task 1 – Add a page for upcoming webinars/online events
- [x] Task 2 – Add a link to this page in the main navigation
- [x] Task 3 – Develop the correct webinar sign-up functionality depending on the user's status (logged-in/logged-out/unregistered)
- [x] Task 4 – Show the webinars that the user has signed up for in their profile/account

### Epic: #9
