### ISSUE TITLE
User Story: Add products

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#53]
As a **Store Owner**, I would like **my employees to be able to add new products to the site easily**, so that **the website is always up to date**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee
**When** I log into my staff account on the website
**Then** I should have additional stock management options available.
- Acceptance Criteria 2
**Given** that I am a logged in employee
**When** I select "Add product"
**Then** I should be directed to a form that allows me to add a new product to the website.
- Acceptance Criteria 3
**Given** that I am a logged-in employe who has completed the form to add a product
**When** I submit the form
**Then** the new product should appear on the website.

### Tasks
- [x] Task 1 – Create a separate navigation bar for employee users (staff) to allow access to other site areas
- [x] Task 2 – Develop a form for employees to add products to the site
- [x] Task 3 – Ensure that product information is completed correctly through form validation
- [x] Task 4 – Develop the backend to process the form data and create a new product file/page to be added to the site

### Epic: #52
