### ISSUE TITLE
User Story: Edit a product

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#54]
As a **Store Owner**, I would like **employees to be able to edit product details on the site easily**, so that **any updates can be carried out when needed**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee
**When** I log into my staff account on the website
**Then** I should have the option to edit any product in the online store.
- Acceptance Criteria 2
**Given** that I am a logged-in employee
**When** I select "Edit product"
**Then**  am directed to a form populated with the existing product data, which I can edit.
- Acceptance Criteria 3
**Given** that I am a logged-in employee
**When** I edit product details within the form and submit the changes
**Then** the changes I made appear on the site for that product.

### Tasks
- [x] Task 1 – Create the option for employees to edit products
- [x] Task 2 – Develop a form for editing a product that is populated with existing product data
- [x] Task 3 – Ensure that product upate information is completed correctly through form validation

### Epic: #52
