### ISSUE TITLE
User Story: Delete a product

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#55]
As a **Store Owner**, I would like **my employees to be able to remove a product from the site**, so that **the store is kept up to date and product that are no longer available can be deleted**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee logged into my staff account
**When** I go to the store's website
**Then** I should have the option to remove any product from the store.
- Acceptance Criteria 2
**Given** that I am an employee logged into my staff account
**When** I select "Remove product"
**Then** I am asked to confirm whether I really want to do it, and I am shown a warning to avoid accidental deletions (defensive programming).
- Acceptance Criteria 3
**Given** that I am an employee logged into my staff account
**When** I have selected to delete a product 
**Then** the product is removed from the shop and the database.

### Tasks
- [x] Task 1 – Create an option to delete any product from the store for admins only
- [x] Task 2 – Use defensive design and warn the user to make sure there are no accidental deletions
- [x] Task 3 – Ensure the product is removed not only from the shop page but also from the database

### Epic: #52
