### ISSUE TITLE
User Story: Add a blog article/recipe

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#57]
As a **Store Owner**, I would like **my employees to be able to add blog articles and healthy recipes easily** so that **any site guests and customers keep visiting the website and feel supported on their health and wellness journey**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee
**When** I log into my staff account and go to the blog page
**Then** I have additional blog management options available.
- Acceptance Criteria 2
**Given** that I am an employee logged into my staff account
**When** I select "Add article/recipe"
**Then** I should be directed to a form that allows me to add a new article/recipe.
- Acceptance Criteria 3
**Given** that I am a logged-in employee and I have completed the form
**When** I submit the form with a new article/recipe
**Then** the new product should appear on the blog page, at the top (newest articles first).

### Tasks
- [x] Task 1 – Create blog navigation specifically for staff members
- [x] Task 2 – Create a form for employees to add an article/recipe to the blog
- [x] Task 3 – Ensure the form is completed correctly through suitable validation
- [x] Task 4 – Develop the backend to process the form data and create a new article/recipe to be added to the blog

### Epic: #56
