### ISSUE TITLE
User Story: Update a blog article/recipe

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#58]
As a **Store Owner**, I would like **my employees to be able to update blog articles and healthy recipes easily** so that **the blog's content is of the highest quality and up to date**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee logged into my staff account
**When** I select "Update article/recipe"
**Then** I should be directed to a form that allows me to edit an existing article or recipe.
- Acceptance Criteria 2
**Given** that I am a logged-in employee and I have completed the form to edit an article/recipe
**When** I submit the form with the updated article/recipe
**Then** the edited version of this article/recipe should be shown on the blog page.

### Tasks
- [ ] Task 1 – Create a form for employees to update an article/recipe
- [ ] Task 2 – Ensure the form is completed correctly through suitable validation
- [ ] Task 3 – Develop the backend to process the form data and update the edited content of the article/recipe

### Epic: #56
