### ISSUE TITLE
User Story: Add an online event/webinar

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#60]
As a **Store Owner**, I would like **my employees to be able to add any online events (webinars) easily** so that **site guests and customers feel supported on their health and wellness journey and belong to a community of like-minded people**.

###vAcceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee
**When** I log into my staff account and go to the online events page
**Then** I have additional webinar options available.
- Acceptance Criteria 2
**Given** that I am an employee logged into my staff account
**When** I select "Add a webinar"
**Then** I should be directed to a form that allows me to add a new webinar.
- Acceptance Criteria 3
**Given** that I am a logged-in employee and I have completed the form
**When** I submit the form with a new webinar
**Then** the new webinar should appear on the online events page.

### Tasks
- [x] Task 1 – Create online events navigation specifically for staff members
- [x] Task 2 – Create a form for employees to add a webinar to the online events
- [x] Task 3 – Ensure the form is completed correctly through suitable validation
- [x] Task 4 – Develop the backend to process the form data and create a new webinar in the database

### Epic: #56
