### ISSUE TITLE
User Story: Edit an online event (webinar)

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#61]
As a **Store Owner**, I would like **my employees to be able to update webinars easily** so that **the content on the online events page is up to date**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given that I am an employee logged into my staff account
**When I select "Update webinar"
**Then I should be directed to a form that allows me to edit an existing online event.
- Acceptance Criteria 3
**Given that I am a logged-in employee and I have completed the form to edit details of a webinar
**When I submit the form with the updated webinar
**Then the edited version of this webinar's details should be shown on the online events page.

### Tasks
- [x] Task 1 – Create a form for employees to update details of a webinar
- [x] Task 2 – Ensure the form is completed correctly through suitable validation
- [x] Task 3 – Develop the backend to process the form data and update the details of the edited webinar

### Epic: #56
