### ISSUE TITLE
User Story: Remove a webinar

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/health-store#62]
As a **Store Owner**, I would like **my employees to be able to remove a past webinar easily** so that **any content that is out-of-date is not visible to our users**.

### Acceptance Criteria
- Acceptance Criteria 1
**Given** that I am an employee logged into my staff account
**When** I select "Remove webinar" on the online events page
**Then** I should be asked to confirm my choice to avoid accidental removal of content.
- Acceptance Criteria 2
**Given** that I am a logged-in employee who clicked "Remove webinar"
**When** and I have confirmed that I want to remove the past webinar
**Then** the webinar disappears from the online events page.

### Tasks
- [ ] Task 1 – Create an option in the employee online events listing to unpublish a webinar (only for past events)
- [ ] Task 2 – Ensure to confirm that the webinar should be removed from the page (defensive programming)
- [ ] Task 3 – Remove the webinar from the online events page but keep it in the database for future reference

### Epic: #56
